### ISSUE TITLE
为博客添加代码块一键复制功能 - Yuze Zou's HomePage 🇨🇳

### ISSUE THREAD

**Issue by zouyu4524** [zouyu4524/zouyu4524.github.io#4]
https://be-my-only.xyz/blog/TeXt-copy-to-clipboard/

 参与开源第一步! 第一次的Pull Request, 献给TeXt。

**Comment by tkbeta** [comment]
您好，祝贺您的first step，我尝试按照PR手动做了以下操作，但是好像没有生效：
1. 手动修改了所有的文件
2. 设置_config.yml -> clipboard: true
3. 紧跟着一个code block后面添加一行{: .copyable}
